# Workflow to check if a user has correctly signed the CLA

name: Check Issue Signed

on:
  issue_comment:
    types: [created]

jobs:
  call-check-signed:
    uses: dfinity/public-workflows/.github/workflows/check_cla_signed.yml@main
    secrets: inherit
